Example/mp4sample supports fragmented mp4
alfg/mp4-rust pull request #46
Opened 2021-01-27 14:22 UTC by nintha

1. Example/mp4sample supports fragmented mp4.
2. Add some fields into trun box :
    - first_sample_flags
    - sample_durations 
    - sample_flags
    - sample_cts
3. And set correct flag in trun box.

2021-01-28 01:44 UTC, alfg requested changes
Hey @nintha, 

Thanks again for the fix. I tried running the `mp4sample` on one of my test fragmented example and got the following issue at the end:

```
...
[14997] start_time=14996000 duration=1000 rendering_offset=0 size=114 is_sync=false
[14998] start_time=14997000 duration=1000 rendering_offset=0 size=124 is_sync=false
[14999] start_time=14998000 duration=1000 rendering_offset=0 size=105 is_sync=false
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })', examples\mp4sample.rs:37:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\mp4sample.exe fragmented.mp4` (exit code: 101)
```

Can you check into this? I've attached the reference file. Thanks.

https://user-images.githubusercontent.com/702541/106077835-2296d200-60c7-11eb-8a0f-1ea337c0e1c6.mp4

2021-01-28 01:44 UTC, alfg commented on src/track.rs
> +                    let sample_count = trun.sample_count;
Possible to utilize `self.sample_count()`?

2021-01-28 01:44 UTC, alfg commented on src/track.rs
> +                    let sample_count = trun.sample_count;
Also here, if possible. Unless it can't be used here.

2021-01-28 14:59 UTC, nintha commented
Hi @alfg
Thanks for your comments, and I try to fix it :
1. Field data_offset in TrunBox is optional. The `fragmented.mp4` does not have data_offset in TrunBox.  
2. Extract duplicated codes as a  new function.

Now `mp4sample` works well with `fragmented.mp4`.

2021-01-29 03:52 UTC, merged

2021-01-29 03:52 UTC, alfg commented
@nintha Thanks for fixing!